### PR TITLE
Reffects store useSelector hook

### PR DESCRIPTION
**Pull request by mariosanchez**
### Summary

I'm doing this just as a experiment, it's not related with any need in the projects using the library.

It's still in progress, but I wish to know your opinion, and any feedback or contribution is wellcome.

Possible benefits of using this:
- No component wrapping, neither mapStatToProps logic. Good for components doing just one subscription for example.
- Less bundle size in the project, since it's not using class components to wrap the subscription.

Cons:
- By the moment I didn' resolved what happens if a components needs to re-render many times because is using multiple selectors with the hook, each selector will provoque a re-render if it's selected state changes (not if it doesn't, this is working right now).
- It has not much benefit for subscribed components that we want to have in Storybook, for example, no big gain since we would need to wrap de component and pass the selector result through properties. It's also true that this doesn't happen often, since we usually put in Storybook only library component (that are not subscribed by definition).

### CODE REVIEW

**Comment by alexhoma** [comment]
Holy peanuts! I like it so much!! 😁

- Agree with all proposed "pros"; and in addition to the first "pro", in my opinion this makes the component easier to read.

- Regarding to the second "con" if we had a component that really matches with the second "con" we could decide not using the hook in this case and use the `subscribe()`; or even create a small high order function that wraps the dumb component and uses the hook for the production code, and export the dumb component for storybook. It's just an idea.

**Comment by mariosanchez** [comment]
It happens that what I said that useSelector provokes re-renders on consecutive calls it's not happening at all. Just commited a test that proves that.

**Comment by mariosanchez** [comment]
Added example and docs

**Comment by alexhoma** [comment]
Wow! I think it will reduce some boilerplate and improve readability in state subscriptions. Should we consider to merge this PR @mariosanchez @trikitrok @rubendm92 ?

**Comment by rubendm92** [comment]
I think it's super cool how it reduces the boilerplate of `mapStateToProps` but I'm not sure if this is what we want.
I thought we usually avoid dispatching events inside the components to not couple them to reffects, using the injectedProps. If we introduce the `useSelector` it would be another way of coupling the "pure" component to the reffects framework.

If we want to have two ways of subscribing to the state (one of them more coupled than the other) it's ok for me, I just wanted to mention it.

Besides that, you said "Good for components doing just one subscription for example". That does mean that you can't use multiple `useSelector` in one component?

**Comment by mariosanchez** [comment]
> I think it's super cool how it reduces the boilerplate of `mapStateToProps` but I'm not sure if this is what we want.
> I thought we usually avoid dispatching events inside the components to not couple them to reffects, using the injectedProps. If we introduce the `useSelector` it would be another way of coupling the "pure" component to the reffects framework.
> 
> If we want to have two ways of subscribing to the state (one of them more coupled than the other) it's ok for me, I just wanted to mention it.

Offering another way to subscribe is kind of my goal, but I have to say, since we're not testing the react part, and the hook is tested, well, maybe is not such a big deal. But not mean to change the way we use it now in our projects if we'are not okay with doing it, I totally agree on the coupling part, it's a tradeoff.

You could also use a "container component" so you could avoid this but maybe you keep having a huge boilerplate:

It would look like this:
```js
import React from "react";
import { dispatch } from "packages/reffects/dist/reffects.es";
import { useSelector } from "packages/reffects-store/dist/reffects-store.es";
function Counter({ 
    count,
    onClickIncrement, 
    onClickDecrement
}) {
  return (
    <>
      <span>{count}</span>
      <button onClick={onClickIncrement}>+</button>
      <button onClick={onClickDecrement}>-</button>
    </>
  );
}

export default function CounterContainer() {
  const count = useSelector(countSelector);
  return (
    <Counter 
            count={count} 
            onClickIncrement={() => dispatch("INCREMENT_COUNTER")}
            onClickDecrement={() => dispatch("DECREMENT_COUNTER")}
      />
  );
}

// Example of a simple selector
function countSelector(state) {
  return state.count;
}
```
Which is more boilerplate than the `subscribe`. 

> Besides that, you said "Good for components doing just one subscription for example". That does mean that you can't use multiple `useSelector` in one component?

I was wrong with this part, you could absolutely do it, and it won't affect the re-renders.

**Review by rubendm92 — APPROVED** [review]

**Comment by trikitrok** [comment]
Merged

**Pull request merged**
